// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu_yy0Wf0Oa3UFSw_JB-LRybBg1Qyvp5o',
    appId: '1:884134553754:web:5021c929e3523616ab9723',
    messagingSenderId: '884134553754',
    projectId: 'wanjaii',
    authDomain: 'wanjaii.firebaseapp.com',
    storageBucket: 'wanjaii.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6ahbii6RzpCxT3iaLq9lqs7nMRa9s5Mk',
    appId: '1:884134553754:android:4ec6845193b6ee42ab9723',
    messagingSenderId: '884134553754',
    projectId: 'wanjaii',
    storageBucket: 'wanjaii.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPtQtSsVwA3fN118KzHRO1nbQA0ZnPRdQ',
    appId: '1:884134553754:ios:6746c9d7b2a6a8c1ab9723',
    messagingSenderId: '884134553754',
    projectId: 'wanjaii',
    storageBucket: 'wanjaii.appspot.com',
    iosBundleId: 'com.google.firebase.presents.newwanjaii',
  );
}
